/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desing_assignmnet2;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Puttipat
 */
public class Game extends javax.swing.JFrame {

    String[][] quiz = new String[10][6];
    private ArrayList<QuizQuestions> questions;
    int question = 0;
    int score = 0;
    int life = 3;
    int skip = 1;
    
    public Game() {
        initComponents();
        generateQuestion();
        update();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
    }
    
    public void update(){
       
     
        QuestionsTextField.setText(quiz[question][0]);
        QuestionsTextField.setEditable(false);
        jLabel2.setText(""+score);
        lifeLabel.setText("You have "+life+" 50/50 left");
        skipLabel.setText("You have "+skip+" skip left");
        ansButton1.setText(quiz[question][1]);
        ansButton2.setText(quiz[question][2]);
        ansButton3.setText(quiz[question][3]);
        ansButton4.setText(quiz[question][4]);
        
        
        
        if(score == 1){
          scoreLabel1.setBackground(Color.GREEN);
          scoreLabel1.setOpaque(true);
        }
        if(score == 2){
          scoreLabel2.setBackground(Color.GREEN);
          scoreLabel2.setOpaque(true);
        }
        if(score == 3){
          scoreLabel3.setBackground(Color.GREEN);
          scoreLabel3.setOpaque(true);
        }
        if(score == 4){
          scoreLabel4.setBackground(Color.GREEN);
          scoreLabel4.setOpaque(true);
        }
        if(score == 5){
          scoreLabel5.setBackground(Color.GREEN);
          scoreLabel5.setOpaque(true);
        }
        if(score == 6){
          scoreLabel5.setBackground(Color.GREEN);
          scoreLabel5.setOpaque(true);
        }
        if(score == 7){
          scoreLabel5.setBackground(Color.GREEN);
          scoreLabel5.setOpaque(true);
        }
        if(score == 8){
          scoreLabel5.setBackground(Color.GREEN);
          scoreLabel5.setOpaque(true);
        }
        if(score == 9){
          scoreLabel5.setBackground(Color.GREEN);
          scoreLabel5.setOpaque(true);
        }
        if(score == 10){
          scoreLabel5.setBackground(Color.GREEN);
          scoreLabel5.setOpaque(true);
        }
        
        
        if (question >= 5)
        {
        QuizEnd quizend= new QuizEnd();
        quizend.setVisible(true);
        
        
        }
        
    }
    
    public void generateQuestion(){
        quiz[0][0] = "3.Who is the only British politician to have held all four “Great Offices of State” at some point during their career?\n";
        quiz[0][1] = "Choice 1";
        quiz[0][2] = "button 2";
        quiz[0][3] = "button 3";
        quiz[0][4] = "button 4";
        quiz[0][5] = "1";
        
        quiz[1][0] = "Question2";
        quiz[1][1] = "Choice 1";
        quiz[1][2] = "button 2";
        quiz[1][3] = "button 3";
        quiz[1][4] = "button 4";
        quiz[1][5] = "2";
        
        quiz[2][0] = "Question3";
        quiz[2][1] = "Choice 1";
        quiz[2][2] = "button 2";
        quiz[2][3] = "button 3";
        quiz[2][4] = "button 4";
        quiz[2][5] = "3";
        
        quiz[3][0] = "Question4";
        quiz[3][1] = "Choice 1";
        quiz[3][2] = "button 2";
        quiz[3][3] = "button 3";
        quiz[3][4] = "button 4";
        quiz[3][5] = "4";
        
        quiz[4][0] = "Question5";
        quiz[4][1] = "Choice 1";
        quiz[4][2] = "button 2";
        quiz[4][3] = "button 3";
        quiz[4][4] = "button 4";
        quiz[4][5] = "1";
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ansButton1 = new javax.swing.JButton();
        ansButton2 = new javax.swing.JButton();
        ansButton3 = new javax.swing.JButton();
        ansButton4 = new javax.swing.JButton();
        skipButton = new javax.swing.JButton();
        lifeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scoreLabel1 = new javax.swing.JLabel();
        scoreLabel2 = new javax.swing.JLabel();
        scoreLabel3 = new javax.swing.JLabel();
        scoreLabel4 = new javax.swing.JLabel();
        scoreLabel5 = new javax.swing.JLabel();
        scoreLabel6 = new javax.swing.JLabel();
        scoreLabel7 = new javax.swing.JLabel();
        scoreLabel8 = new javax.swing.JLabel();
        scoreLabel9 = new javax.swing.JLabel();
        scoreLabel10 = new javax.swing.JLabel();
        skipLabel = new javax.swing.JLabel();
        lifeLabel = new javax.swing.JLabel();
        QuestionsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ansButton1.setText("jButton1");
        ansButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton1ActionPerformed(evt);
            }
        });

        ansButton2.setText("jButton2");
        ansButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton2ActionPerformed(evt);
            }
        });

        ansButton3.setText("jButton3");
        ansButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton3ActionPerformed(evt);
            }
        });

        ansButton4.setText("jButton4");
        ansButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton4ActionPerformed(evt);
            }
        });

        skipButton.setText("Skip");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });

        lifeButton.setText("50/50");
        lifeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifeButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        scoreLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel1.setText("100,000");
        scoreLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel2.setText("200,000");
        scoreLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel3.setText("300,000");
        scoreLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel4.setText("400,000");
        scoreLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel5.setText("500,000");
        scoreLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel6.setText("600,000");
        scoreLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel7.setText("700,000");
        scoreLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel8.setText("800,000");
        scoreLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel9.setText("900,000");
        scoreLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scoreLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel10.setText("1,000,000");
        scoreLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        skipLabel.setText("jLabel3");

        lifeLabel.setText("jLabel4");

        QuestionsTextField.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(skipButton)
                                        .addGap(130, 130, 130)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(skipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lifeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lifeButton)
                                        .addGap(113, 113, 113))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ansButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(ansButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ansButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ansButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(QuestionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scoreLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(scoreLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(QuestionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lifeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lifeButton)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(skipLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(skipButton)
                                .addGap(6, 6, 6)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ansButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ansButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ansButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ansButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(scoreLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ansButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton1ActionPerformed
        // TODO add your handling code here:
        if(quiz[question][5]=="1") {
            score++;
        } 
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        
        
        if(life>0){
            lifeButton.setEnabled(true);
        }
       
        
        
        question++;
        update();
    }//GEN-LAST:event_ansButton1ActionPerformed

    private void ansButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton2ActionPerformed
        // TODO add your handling code here:
         if(quiz[question][5]=="2") {
            score++;
        }
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        
        
        if(life>0){
            lifeButton.setEnabled(true);
        }
        
        question++;
        update();
       
    }//GEN-LAST:event_ansButton2ActionPerformed

    private void ansButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton3ActionPerformed
        // TODO add your handling code here:
         if(quiz[question][5]=="3") {
            score++;
        }
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
       
        
        if(life>0){
            lifeButton.setEnabled(true);
        }
        
        question++;
        update();
        
    }//GEN-LAST:event_ansButton3ActionPerformed

    private void ansButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton4ActionPerformed
        // TODO add your handling code here:
         if(quiz[question][5]=="4") {
            score++;
        }
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        
        
        if(life>0){
            lifeButton.setEnabled(true);
        }
        
        question++;
        update();
        
    }//GEN-LAST:event_ansButton4ActionPerformed

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        // TODO add your handling code here:
        skip--;
        
        if(skip == 0){
            skipButton.setEnabled(false);
        }
        question++;
        update();
       
    }//GEN-LAST:event_skipButtonActionPerformed

    private void lifeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lifeButtonActionPerformed
        // TODO add your handling code here:
        
        if(life >= 1){
                    life--;

        if(quiz[question][5]=="1" && quiz[question][5]!="2" && quiz[question][5]!="3" && quiz[question][5]!="4" ) {
           
            ansButton3.setEnabled(false);
            ansButton4.setEnabled(false);
            lifeButton.setEnabled(false);
            
            
        }else if(quiz[question][5]!="1" && quiz[question][5]=="2" && quiz[question][5]!="3" && quiz[question][5]!="4" ) {
           
            ansButton1.setEnabled(false);
            ansButton3.setEnabled(false);
            lifeButton.setEnabled(false);
        }else if(quiz[question][5]!="1" && quiz[question][5]!="2" && quiz[question][5]=="3" && quiz[question][5]!="4" ) {
           
            ansButton2.setEnabled(false);
            ansButton4.setEnabled(false);
            lifeButton.setEnabled(false);
        }else if(quiz[question][5]!="1" && quiz[question][5]!="2" && quiz[question][5]!="3" && quiz[question][5]=="4" ) {
           
            ansButton2.setEnabled(false);
            ansButton3.setEnabled(false);
            lifeButton.setEnabled(false);
        }
        }else if(life == 0){
            lifeButton.setEnabled(false);
        }
        
        
       
        update();
        
        
       
    }//GEN-LAST:event_lifeButtonActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
        if(score == 1){
            jLabel2.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_jLabel2AncestorAdded

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuestionsTextField;
    private javax.swing.JButton ansButton1;
    private javax.swing.JButton ansButton2;
    private javax.swing.JButton ansButton3;
    private javax.swing.JButton ansButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lifeButton;
    private javax.swing.JLabel lifeLabel;
    private javax.swing.JLabel scoreLabel1;
    private javax.swing.JLabel scoreLabel10;
    private javax.swing.JLabel scoreLabel2;
    private javax.swing.JLabel scoreLabel3;
    private javax.swing.JLabel scoreLabel4;
    private javax.swing.JLabel scoreLabel5;
    private javax.swing.JLabel scoreLabel6;
    private javax.swing.JLabel scoreLabel7;
    private javax.swing.JLabel scoreLabel8;
    private javax.swing.JLabel scoreLabel9;
    private javax.swing.JButton skipButton;
    private javax.swing.JLabel skipLabel;
    // End of variables declaration//GEN-END:variables
}
