/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desing_assignmnet2;

/**
 *
 * @author Puttipat
 */
public class Quize_Question extends javax.swing.JFrame {

    String[][] quiz = new String[10][6];
    int question = 0;
    int score = 0;
    int life = 3;
    int skip = 1;
    
    public Quize_Question() {
        initComponents();
        initData();
        update();
    }
    
    public void update(){
        jLabel1.setText(quiz[question][0]);
        ansButton1.setText(quiz[question][1]);
        ansButton2.setText(quiz[question][2]);
        ansButton3.setText(quiz[question][3]);
        ansButton4.setText(quiz[question][4]);
        
        
    }
    
    public void initData(){
        quiz[0][0] = "Question1";
        quiz[0][1] = "Choice 1";
        quiz[0][2] = "button 2";
        quiz[0][3] = "button 3";
        quiz[0][4] = "button 4";
        quiz[0][5] = "1";
        
        quiz[1][0] = "Question2";
        quiz[1][1] = "Choice 1";
        quiz[1][2] = "button 2";
        quiz[1][3] = "button 3";
        quiz[1][4] = "button 4";
        quiz[1][5] = "2";
        
        quiz[2][0] = "Question3";
        quiz[2][1] = "Choice 1";
        quiz[2][2] = "button 2";
        quiz[2][3] = "button 3";
        quiz[2][4] = "button 4";
        quiz[2][5] = "3";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ansButton1 = new javax.swing.JButton();
        ansButton2 = new javax.swing.JButton();
        ansButton3 = new javax.swing.JButton();
        ansButton4 = new javax.swing.JButton();
        skipButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("jLabel1");

        ansButton1.setText("jButton1");
        ansButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton1ActionPerformed(evt);
            }
        });

        ansButton2.setText("jButton2");
        ansButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton2ActionPerformed(evt);
            }
        });

        ansButton3.setText("jButton3");
        ansButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton3ActionPerformed(evt);
            }
        });

        ansButton4.setText("jButton4");
        ansButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansButton4ActionPerformed(evt);
            }
        });

        skipButton.setText("Skip");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });

        helpButton.setText("50/50");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ansButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                    .addComponent(ansButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ansButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                    .addComponent(ansButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(skipButton)
                        .addGap(154, 154, 154)
                        .addComponent(helpButton)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skipButton)
                    .addComponent(helpButton))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ansButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton1ActionPerformed
        // TODO add your handling code here:
        if(quiz[question][5]=="1") {
            score++;
        } 
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        helpButton.setEnabled(true);
        
        question++;
        update();
    }//GEN-LAST:event_ansButton1ActionPerformed

    private void ansButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton2ActionPerformed
        // TODO add your handling code here:
         if(quiz[question][5]=="2") {
            score++;
        }
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        helpButton.setEnabled(true);
        question++;
        update();
    }//GEN-LAST:event_ansButton2ActionPerformed

    private void ansButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton3ActionPerformed
        // TODO add your handling code here:
         if(quiz[question][5]=="3") {
            score++;
        }
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        helpButton.setEnabled(true);
        question++;
        update();
    }//GEN-LAST:event_ansButton3ActionPerformed

    private void ansButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansButton4ActionPerformed
        // TODO add your handling code here:
         if(quiz[question][5]=="4") {
            score++;
        }
        ansButton1.setEnabled(true);
        ansButton2.setEnabled(true);
        ansButton3.setEnabled(true);
        ansButton4.setEnabled(true);
        helpButton.setEnabled(true);
        question++;
        update();
    }//GEN-LAST:event_ansButton4ActionPerformed

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        // TODO add your handling code here:
        skip--;
        
        if(skip == 0){
            skipButton.setEnabled(false);
        }
        question++;
        score--;
        update();
    }//GEN-LAST:event_skipButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        life--;
        
        if(quiz[question][5]=="1" && quiz[question][5]!="2" && quiz[question][5]!="3" && quiz[question][5]!="4" ) {
           
            ansButton3.setEnabled(false);
            ansButton4.setEnabled(false);
            helpButton.setEnabled(false);
            
            
        }else if(quiz[question][5]!="1" && quiz[question][5]=="2" && quiz[question][5]!="3" && quiz[question][5]!="4" ) {
           
            ansButton1.setEnabled(false);
            ansButton3.setEnabled(false);
            helpButton.setEnabled(false);
        }else if(quiz[question][5]!="1" && quiz[question][5]!="2" && quiz[question][5]=="3" && quiz[question][5]!="4" ) {
           
            ansButton2.setEnabled(false);
            ansButton4.setEnabled(false);
            helpButton.setEnabled(false);
        }else if(quiz[question][5]!="1" && quiz[question][5]!="2" && quiz[question][5]!="3" && quiz[question][5]=="4" ) {
           
            ansButton2.setEnabled(false);
            ansButton3.setEnabled(false);
            helpButton.setEnabled(false);
        }
        if(life <= 0){
            helpButton.setEnabled(false);
        }
        
        score--;
        update();
        
       
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quize_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quize_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quize_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quize_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quize_Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ansButton1;
    private javax.swing.JButton ansButton2;
    private javax.swing.JButton ansButton3;
    private javax.swing.JButton ansButton4;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton skipButton;
    // End of variables declaration//GEN-END:variables
}
